name: Build and push image
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - ".devcontainer/**"
      - ".github/dependabot.yml"
      - ".vscode/**"
      - "LICENSE"
      - "README.md"

jobs:
  build_main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [linux-arm-v7, linux-arm64, linux-amd64]

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Detect architecture
        id: detect
        run: |
          ARCHITECTURE=${{ matrix.architecture }}
          echo "platform=${ARCHITECTURE//-/\/}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
          driver-opts: image=moby/buildkit:v0.10.6

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push images using buildx
        run: |
          ARCHITECTURE=${{ matrix.architecture }}
          docker buildx build \
          --output "type=image,push=true" \
          --tag ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF//refs\/heads\//}-${GITHUB_SHA:0:7}-${ARCHITECTURE//linux-/} \
          --build-arg ARCH="${ARCHITECTURE//linux-/}" \
          --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
          --build-arg COMMIT_AUTHOR="$(git log -1 --pretty=format:'%ae')" \
          --build-arg VCS_REF="${GITHUB_SHA}" \
          --build-arg VCS_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" \
          --file ./Dockerfile ./

  publish:
    runs-on: ubuntu-latest
    needs: [build_main]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Enable experimental Docker features
        run: 'echo ''{"experimental": "enabled"}'' > ~/.docker/config.json'

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Create and push docker manifest
        run: |
          docker manifest create ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_SHA:0:7} \
              ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF//refs\/heads\//}-${GITHUB_SHA:0:7}-amd64 \
              ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF//refs\/heads\//}-${GITHUB_SHA:0:7}-arm-v7 \
              ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF//refs\/heads\//}-${GITHUB_SHA:0:7}-arm64
          docker manifest push ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_SHA:0:7}

          if [[ ${GITHUB_REF//refs\/heads\//} == "main" ]]
          then
              docker manifest create ghcr.io/${GITHUB_REPOSITORY}:latest \
                  ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF//refs\/heads\//}-${GITHUB_SHA:0:7}-amd64 \
                  ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF//refs\/heads\//}-${GITHUB_SHA:0:7}-arm-v7 \
                  ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF//refs\/heads\//}-${GITHUB_SHA:0:7}-arm64
              docker manifest push ghcr.io/${GITHUB_REPOSITORY}:latest

              docker manifest create ghcr.io/${GITHUB_REPOSITORY}:amd64 \
                  ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF//refs\/heads\//}-${GITHUB_SHA:0:7}-amd64
              docker manifest push ghcr.io/${GITHUB_REPOSITORY}:amd64

              docker manifest create ghcr.io/${GITHUB_REPOSITORY}:arm-v7 \
                  ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF//refs\/heads\//}-${GITHUB_SHA:0:7}-arm-v7
              docker manifest push ghcr.io/${GITHUB_REPOSITORY}:arm-v7

              docker manifest create ghcr.io/${GITHUB_REPOSITORY}:arm64 \
                  ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF//refs\/heads\//}-${GITHUB_SHA:0:7}-arm64
              docker manifest push ghcr.io/${GITHUB_REPOSITORY}:arm64
          else
              docker manifest create ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF//refs\/heads\//} \
                  ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF//refs\/heads\//}-${GITHUB_SHA:0:7}-amd64 \
                  ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF//refs\/heads\//}-${GITHUB_SHA:0:7}-arm-v7 \
                  ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF//refs\/heads\//}-${GITHUB_SHA:0:7}-arm64
              docker manifest push ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF//refs\/heads\//}
          fi
